version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'Consulting_bot'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'db_password'
    ports:
      - '80:3306'
